### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by ilya**
This PR has two new server tests. They check resiliency against unknown or malformed messages.

I sort of forgot the optimal git workflow so this PR includes the other one. Will it update to show only the new diffs if you merge the other one? Time will tell!

### CODE REVIEW

**Comment by lacker** [comment]
Nice, this is pretty good. I'll just close the other PR. Same two comments:

1. can you remove the un-needed () in your if statements
2. since there's no license in this repo right now, are you ok considering all your pull requests to this project to be released to the public domain

**Comment by lacker** [comment]
It's possible there is some race condition with shut down - it looks like TestBasicNetwork doesn't really clean up after itself, and that might not have been a problem before because that was the only test that tried to bind to ports. I'll add a way to shut these servers down from another thread.

**Comment by lacker** [comment]
OK, well I added the ability for servers to gracefully shut down. It seems like that was likely causing nondeterministic failures - which goroutine actually got to bind to a port seemed racy before. Tests that use ports should work way better now. So great thanks for bringing that to my attention. The downside is I had to refactor the server erroring stuff which maybe has totally borked these PR and at any rate has a lot of merge conflicts ;-)

**Comment by ilya** [comment]
Okay, I'll take a look at fixing the merge.

**Comment by lacker** [comment]
Oops, there is just an old-school infinite loop in Client.sendForever

**Comment by lacker** [comment]
OK, so it was attempting to send every message infinite times in the client logic. I accidentally deleted a break statement before, it looks like. :P The recipients know to ignore it, but still AFAICT that was causing excess cpu usage and perhaps causing some sort of starvation. I fixed that, probably causing yet more merge conflicts, and now there is also one extra test TestSendMoney which does not pass because it is reproducing a bug.

**Comment by lacker** [comment]
OK tests all work now. The port-already-taken test probably doesn't make sense any more, I had to add retries to get tests working in different orders. Testing that the servers can handle garbage is still good though

**Comment by ilya** [comment]
Aren't there still conflicts to fix?

**Comment by ilya** [comment]
Okay, merge fixed and all tests passing. PTAL.

**Comment by lacker** [comment]
Looks good to me. Can you just remove that `.swp` file?

**Comment by ilya** [comment]
Oh, shoot. Fixed.

**Pull request merged**
